# Generated by Django 5.1.7 on 2025-04-03 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('authentication', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Routine',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.faculty_profile')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture_Plan',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('assigned_date', models.DateField()),
                ('assigned_room', models.CharField(max_length=100)),
                ('assigned_method', models.CharField(max_length=100)),
                ('accomplision_status', models.BooleanField(default=False)),
                ('accomplished_date', models.DateField(blank=True, null=True)),
                ('accomplished_room', models.CharField(blank=True, max_length=100, null=True)),
                ('accomplished_method', models.CharField(blank=True, max_length=100, null=True)),
                ('accomplished_faculties', models.ManyToManyField(blank=True, related_name='lecture_plan_accomplished_faculties', to='authentication.faculty_profile')),
                ('assigned_faculties', models.ManyToManyField(related_name='lecture_plan_faculties', to='authentication.faculty_profile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lecture')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('attendance_status', models.BooleanField(default=False)),
                ('attendance_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student_profile')),
                ('lecture_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.lecture_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Preparatory_Class',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_date', models.DateField()),
                ('class_routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class_routine')),
                ('new_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.faculty_profile')),
            ],
        ),
    ]
