# Generated by Django 5.1.7 on 2025-04-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_lecture_plan_referrence_class_routine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterModelOptions(
            name='class_routine',
            options={'verbose_name_plural': 'Class Routines'},
        ),
        migrations.AlterModelOptions(
            name='lecture_plan',
            options={'verbose_name_plural': 'Lecture Plans'},
        ),
        migrations.AlterModelOptions(
            name='preparatory_class',
            options={'verbose_name_plural': 'Preparatory Classes'},
        ),
    ]
