# Generated by Django 5.1.7 on 2025-04-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_routine_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_plan',
            name='accomplished_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture_plan',
            name='accomplished_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lecture_plan',
            name='accomplished_room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
