# Generated by Django 5.1.7 on 2025-04-02 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_lecture_plan_accomplished_date_and_more'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture_plan',
            name='course',
            field=models.ForeignKey(default='BCA47111', on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture_plan',
            name='module',
            field=models.ForeignKey(default='BCA47111-M1', on_delete=django.db.models.deletion.CASCADE, to='courses.module'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture_plan',
            name='id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
