# Generated by Django 5.1.7 on 2025-04-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('classes', '0006_alter_lecture_plan_accomplished_faculties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_plan',
            name='accomplished_faculties',
            field=models.ManyToManyField(blank=True, related_name='lecture_plan_accomplished_faculties', to='authentication.faculty_profile'),
        ),
    ]
