# Generated by Django 5.1.7 on 2025-04-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty_profile',
            options={'verbose_name_plural': 'Faculty Profiles'},
        ),
        migrations.AlterModelOptions(
            name='student_profile',
            options={'verbose_name_plural': 'Student Profiles'},
        ),
    ]
