# Generated by Django 5.1.7 on 2025-04-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_faculty_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty_profile',
            options={'verbose_name': 'Faculty Profile', 'verbose_name_plural': 'Faculty Profiles'},
        ),
        migrations.AlterModelOptions(
            name='student_profile',
            options={'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
    ]
