# Generated by Django 5.1.7 on 2025-04-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='sections',
            field=models.ManyToManyField(related_name='semesters', to='academics.section'),
        ),
    ]
