# Generated by Django 5.1.7 on 2025-04-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='semesters',
            field=models.ManyToManyField(blank=True, related_name='batch_semester', to='academics.semester'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='semester_courses', to='courses.course'),
        ),
    ]
