# Generated by Django 5.1.7 on 2025-04-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_batch_semesters_alter_semester_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name_plural': 'Semesters'},
        ),
    ]
