# Generated by Django 5.1.7 on 2025-04-06 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_batch_options_alter_department_options_and_more'),
        ('authentication', '0002_alter_faculty_profile_options_and_more'),
        ('courses', '0002_alter_course_options_alter_lecture_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester_Course_Faculty',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('faculty', models.ManyToManyField(blank=True, related_name='faculty_semester_courses', to='authentication.faculty_profile')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
            ],
            options={
                'verbose_name_plural': 'Semester Course Faculty',
            },
        ),
    ]
