# Generated by Django 5.1.7 on 2025-04-01 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('authentication', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('assignment1', models.IntegerField()),
                ('assignment2', models.IntegerField()),
                ('ppt', models.IntegerField()),
                ('class_test1', models.IntegerField()),
                ('class_test2', models.IntegerField()),
                ('final', models.IntegerField()),
                ('total', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('percentage', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student_profile')),
            ],
        ),
    ]
