# Generated by Django 5.1.7 on 2025-04-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marks',
            options={'verbose_name': 'Marks', 'verbose_name_plural': 'Marks'},
        ),
    ]
